In [2]:
import numpy as np
import pandas as pd


In [3]:
demand = np.array([1, 2, 3, 4, 5])  # kW half hourly data 

nHouses = 3

dt = 0.5    # hr 

output1 = demand * nHouses
output2 = output1 * dt

print(demand)
print(demand.shape)
print(output1)
print(output2)


[1 2 3 4 5]
(5,)
[ 3  6  9 12 15]
[1.5 3.  4.5 6.  7.5]


## How to add an index to CSV 

- I did it manually by creating a vector of ascending values and then appending that column to my column of data (so I had 2 columns in my numpy array). Then I converted the numpy to a dataframe then wrote it to a csv file 
- a quicker way to do the same thing is just to set the 'index' parameter = True when using the df.to_csv function

In [4]:
x = np.arange(1,5)
y = np.arange(5,9)


x = np.reshape(x,(x.shape[0],1))
y = np.reshape(y,(y.shape[0],1))


z = np.concatenate((x,y),axis=1)

print(x)
print(x.shape)
print(y)
print(z)

[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[5]
 [6]
 [7]
 [8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [5]:
df = pd.DataFrame(z,columns=['index','power (kW)'])
print(df)

   index  power (kW)
0      1           5
1      2           6
2      3           7
3      4           8


In [6]:
# by setting index = "False" we will not have an index in our CSV file
df.to_csv('tester1.csv',index=False)

# by setting the index parameter = "True" we will have a first column in our data which is an index starting at 0 and counting up 
df.to_csv('tester2.csv',index=True)

## Tester of indexing in python


In [11]:
a = np.array([5,8,4,9,6,2])
x = a[1:4]
y = a[4:]
z = np.append(x,y)


print(z)




[8 4 9 6 2]


## Misc

- figure out what the following line does:
 nondom = [i[0] for i in load_site2.getOutput(dt).tolist()]  


In [24]:
a = np.array([[5],[8],[4],[9],[6],[2]])
print(a)
a = a.tolist()
print(a)
 
nondom = [i[0] for i in a]  

print(nondom)

[[5]
 [8]
 [4]
 [9]
 [6]
 [2]]
[[5], [8], [4], [9], [6], [2]]
[5, 8, 4, 9, 6, 2]


In [28]:
x = np.array([5,8,4,9,6,2])
print(x)
print(type(x))

list_x = [i for i in x]

print(list_x)
print(type(list_x))

[5 8 4 9 6 2]
<class 'numpy.ndarray'>
[5, 8, 4, 9, 6, 2]
<class 'list'>
